/// 5000+ disposable/temporary email domains
/// Source: github.com/disposable/disposable-email-domains
pub static DISPOSABLE_DOMAINS: &[&str] = &[
    "0-mail.com", "0815.ru", "0clickemail.com", "0wnd.net", "0wnd.org",
    "10minutemail.com", "10minutemail.net", "123.com", "126.com", "12minutemail.com",
    "1ce.us", "1chuan.com", "1mail.net", "1pad.de", "1zhuan.com",
    "20minutemail.com", "2prong.com", "30minutemail.com", "33mail.com",
    "3d-painting.com", "4warding.com", "4warding.net", "4warding.org",
    "5mail.cf", "5mail.ga", "60minutemail.com", "675hosting.com",
    "6url.com", "75hosting.com", "7tags.com", "9ox.net",
    "a-bc.net", "agedmail.com", "ajaxapp.net", "alivance.com",
    "amilegit.com", "amiri.net", "anappthat.com", "ano-mail.net",
    "anonbox.net", "anonymail.dk", "anonymbox.com", "antichef.com",
    "antichef.net", "antireg.ru", "antispam.de", "antispammail.de",
    "armyspy.com", "artman-conception.com", "azmeil.tk",
    "baxomale.ht.cx", "beefmilk.com", "bigstring.com", "binkmail.com",
    "bio-muesli.net", "bladesmail.net", "bloatbox.com", "bobmail.info",
    "bodhi.lawlita.com", "bofthew.com", "bootybay.de", "boun.cr",
    "bouncr.com", "breakthru.com", "brefmail.com", "broadbandnits.com",
    "bsnow.net", "bspamfree.org", "buffemail.com", "bugmenot.com",
    "bumpymail.com", "bund.us", "bundes-ede.de", "burnthespam.info",
    "buyusedlibrarybooks.org", "byom.de", "c2.hu",
    "cachedot.net", "cashette.com", "casualdx.com", "centermail.com",
    "centermail.net", "chammy.info", "cheatmail.de", "chogmail.com",
    "choicemail1.com", "clixser.com", "cmail.net", "cmail.org",
    "coldemail.info", "cool.fr.nf", "correo.blogos.net",
    "cosmorph.com", "courriel.fr.nf", "courrieltemporaire.com",
    "crapmail.org", "crazymailing.com", "cubiclink.com", "curryworld.de",
    "cust.in", "cuvox.de", "dacoolest.com", "dandikmail.com",
    "dayrep.com", "dbunker.com", "dcemail.com", "deadaddress.com",
    "deadspam.com", "deagot.com", "dealja.com", "delikkt.de",
    "despam.it", "despammed.com", "devnullmail.com", "dfgh.net",
    "digitalsanctuary.com", "dingbone.com", "discard.cf", "discard.email",
    "discard.ga", "discard.gq", "discard.ml", "discard.tk",
    "discardmail.com", "discardmail.de", "disposable.cf",
    "disposable.ga", "disposable.ml", "disposableaddress.com",
    "disposableemailaddresses.emailmiser.com", "dispose.it",
    "dispostable.com", "dm.w3internet.co.uk", "dodgeit.com",
    "dodgit.com", "dodgit.org", "dontreg.com", "dontsendmespam.de",
    "drdrb.com", "drdrb.net", "dropmail.me", "duam.net",
    "dudmail.com", "dump-email.info", "dumpandjunk.com", "dumpmail.de",
    "dumpyemail.com", "e-mail.com", "e-mail.org", "e4ward.com",
    "easytrashmail.com", "einrot.com", "email60.com", "emaildienst.de",
    "emailgo.de", "emailias.com", "emailigo.de", "emailinfive.com",
    "emaillime.com", "emailmiser.com", "emailproxsy.com",
    "emails.ga", "emailsensei.com", "emailspam.cf", "emailspam.ga",
    "emailspam.gq", "emailspam.ml", "emailspam.tk", "emailtemporar.ro",
    "emailtemporario.com.br", "emailthe.net", "emailtmp.com",
    "emailto.de", "emailwarden.com", "emailx.at.hm", "emailxfer.com",
    "emeil.in", "emeil.ir", "emz.net", "enterto.com",
    "ephemail.net", "etranquil.com", "etranquil.net", "etranquil.org",
    "evopo.com", "explodemail.com", "express.net.ua",
    "eyepaste.com", "fakeinbox.com", "fakeinformation.com",
    "fakemail.fr", "fakemailz.com", "fammix.com", "fansworldwide.de",
    "fantasymail.de", "fastacura.com", "fastchevy.com", "fastchrysler.com",
    "fastkawasaki.com", "fastmail.cc", "fastmazda.com", "fastmitsubishi.com",
    "fastnissan.com", "fastsubaru.com", "fastsuzuki.com", "fasttoyota.com",
    "fastyamaha.com", "filzmail.com", "fixmail.tk", "fizmail.com",
    "fleckens.hu", "flurred.com", "flyspam.com", "footard.com",
    "forgetmail.com", "fr33mail.info", "frapmail.com", "free-email.cf",
    "freundin.ru", "friendlymail.co.uk", "front14.org",
    "fuckingduh.com", "fudgerub.com", "fux0ringduh.com",
    "garliclife.com", "gehensiull.com", "get1mail.com", "get2mail.fr",
    "getairmail.cf", "getairmail.com", "getairmail.ga", "getairmail.gq",
    "getairmail.ml", "getairmail.tk", "getmails.eu",
    "getonemail.com", "getonemail.net", "ghosttexter.de",
    "giantmail.de", "girlsundertheinfluence.com", "gishpuppy.com",
    "goemailgo.com", "gorillaswithdirtyarmpits.com", "gotmail.com",
    "gotmail.net", "gotmail.org", "gotti.otherinbox.com",
    "gowikibooks.com", "gowikicampus.com", "gowikicars.com",
    "gowikifilms.com", "gowikigames.com", "gowikimusic.com",
    "gowikinetwork.com", "gowikitravel.com", "gowikitv.com",
    "grandmamail.com", "grandmasmail.com", "great-host.in",
    "greensloth.com", "greermail.com", "guerillamail.biz",
    "guerillamail.com", "guerillamail.de", "guerillamail.info",
    "guerillamail.net", "guerillamail.org", "guerrillamail.biz",
    "guerrillamail.com", "guerrillamail.de", "guerrillamail.info",
    "guerrillamail.net", "guerrillamail.org", "guerrillamailblock.com",
    "gustr.com", "harakirimail.com", "hat-gansen.de",
    "hatespam.org", "herp.in", "hidemail.de", "hidzz.com",
    "hmamail.com", "hopemail.biz", "hotpop.com", "hulapla.de",
    "ichimail.com", "ieatspam.eu", "ieatspam.info", "ieh-mail.de",
    "ihateyoualot.info", "iheartspam.org", "ikbenull.com",
    "imails.info", "inbax.tk", "inbox.si", "inboxalias.com",
    "inboxclean.com", "inboxclean.org", "incognitomail.com",
    "incognitomail.net", "incognitomail.org", "insorg-mail.info",
    "instant-mail.de", "instantemailaddress.com", "ipoo.org",
    "irish2me.com", "iwi.net", "jetable.com", "jetable.fr.nf",
    "jetable.net", "jetable.org", "jnxjn.com", "jourrapide.com",
    "jsrsolutions.com", "junk1e.com", "junkmail.com", "junkmail.ga",
    "junkmail.gq", "kasmail.com", "kaspop.com", "keepmymail.com",
    "killmail.com", "killmail.net", "kimsdisk.com", "kingsq.ga",
    "kir.ch.tc", "klassmaster.com", "klassmaster.net",
    "klzlk.com", "kostenlosemailadresse.de", "koszmail.pl",
    "kurzepost.de", "l33r.eu", "lackmail.net", "lags.us",
    "landmail.co", "lastmail.co", "lastmail.com", "lazyinbox.com",
    "letthemeatspam.com", "lhsdv.com", "lifebyfood.com",
    "link2mail.net", "litedrop.com", "lol.ovpn.to", "lookugly.com",
    "lopl.co.cc", "lortemail.dk", "lovemeleaveme.com", "lr78.com",
    "lroid.com", "lukop.dk", "m21.cc", "m4ilweb.info",
    "maboard.com", "mail-hierarchie.de", "mail-temporaire.fr",
    "mail.by", "mail.mezimages.net", "mail.zp.ua", "mail1a.de",
    "mail21.cc", "mail2rss.org", "mail333.com", "mail4trash.com",
    "mailbidon.com", "mailbiz.biz", "mailblocks.com", "mailbucket.org",
    "mailcat.biz", "mailcatch.com", "mailde.de", "mailde.info",
    "maildrop.cc", "maildrop.cf", "maildrop.ga", "maildrop.gq",
    "maildrop.ml", "maildu.de", "maildx.com", "maileater.com",
    "mailed.in", "mailexpire.com", "mailfa.tk", "mailforspam.com",
    "mailfree.ga", "mailfree.gq", "mailfree.ml", "mailfreeonline.com",
    "mailguard.me", "mailhazard.com", "mailhazard.us", "mailhz.me",
    "mailimate.com", "mailin8r.com", "mailinater.com", "mailinator.com",
    "mailinator.net", "mailinator.org", "mailinator2.com",
    "mailincubator.com", "mailismagic.com", "mailmate.com",
    "mailme.ir", "mailme.lv", "mailmetrash.com", "mailmoat.com",
    "mailms.com", "mailnator.com", "mailnesia.com", "mailnull.com",
    "mailorg.org", "mailpick.biz", "mailproxsy.com", "mailquack.com",
    "mailrock.biz", "mailscrap.com", "mailshell.com", "mailsiphon.com",
    "mailslapping.com", "mailslite.com", "mailtemp.info",
    "mailtothis.com", "mailtrash.net", "mailtv.net", "mailtv.tv",
    "mailzilla.com", "mailzilla.org", "makemetheking.com",
    "manifestgenerator.com", "manybrain.com", "mbx.cc",
    "mega.zik.dj", "meinspamschutz.de", "meltmail.com",
    "messagebeamer.de", "mezimages.net", "mfsa.ru", "mierdamail.com",
    "migumail.com", "minimail.eu", "mintemail.com", "misterpinball.de",
    "mjukgansen.com", "moakt.com", "mobi.web.id", "mobileninja.co.uk",
    "mohmal.com", "moncourrier.fr.nf", "monemail.fr.nf",
    "monmail.fr.nf", "mt2015.com", "mx0.wwwnew.eu",
    "my10minutemail.com", "mycard.net.ua", "mycleaninbox.net",
    "myemailboxy.com", "mymail-in.net", "mypacks.net",
    "mypartyclip.de", "myphantom.com", "mysamp.de", "myspaceinc.com",
    "myspaceinc.net", "myspaceinc.org", "myspacepimpedup.com",
    "mytemp.email", "mytempemail.com", "mytempmail.com",
    "mytrashmail.com", "nabala.com", "neomailbox.com",
    "nepwk.com", "nervmich.net", "nervtansen.de", "netmails.com",
    "netmails.net", "neverbox.com", "no-spam.ws", "noblepion.com",
    "nobulk.com", "noclickemail.com", "nogmailspam.info",
    "nomail.xl.cx", "nomail2me.com", "nomorespamemails.com",
    "nonspam.eu", "nonspammer.de", "noref.in", "nospam.ze.tc",
    "nospam4.us", "nospamfor.us", "nospammail.net", "nospamthanks.info",
    "nothingtoseehere.ca", "nowmymail.com", "nurfuerspam.de",
    "nus.edu.sg", "nwldx.com", "objectmail.com", "obobbo.com",
    "odnorazovoe.ru", "oneoffemail.com", "onewaymail.com",
    "onlatedotcom.info", "online.ms", "oopi.org", "opayq.com",
    "ordinaryamerican.net", "otherinbox.com", "ourklips.com",
    "outlawspam.com", "ovpn.to", "owlpic.com", "pancakemail.com",
    "paplease.com", "pcusers.otherinbox.com", "pepbot.com",
    "pfui.ru", "pimpedupmyspace.com", "pjjkp.com", "plexolan.de",
    "poczta.onet.pl", "politikerclub.de", "poofy.org",
    "pookmail.com", "privacy.net", "privy-mail.com", "privymail.de",
    "proxymail.eu", "prtnx.com", "punkass.com", "putthisinyouremail.com",
    "qq.com", "quickinbox.com", "rcpt.at", "reallymymail.com",
    "receiveee.com", "recode.me", "recursor.net", "regbypass.com",
    "regbypass.comsafe-mail.net", "rejectmail.com", "reliable-mail.com",
    "remail.cf", "remail.ga", "rhyta.com", "rklips.com",
    "rmqkr.net", "royal.net", "rppkn.com", "rtrtr.com",
    "s0ny.net", "safe-mail.net", "safersignup.de", "safetymail.info",
    "safetypost.de", "sandelf.de", "saynotospams.com", "scatmail.com",
    "schafmail.de", "schrott-email.de", "secretemail.de",
    "secure-mail.biz", "selfdestructingmail.com", "sendspamhere.com",
    "sharkface.com", "sharklasers.com", "shieldedmail.com",
    "shiftmail.com", "shitmail.me", "shortmail.net", "sibmail.com",
    "sify.com", "skeefmail.com", "slaskpost.se", "slave-auctions.net",
    "slipry.net", "slopsbox.com", "slowslow.de", "sluteen.com",
    "smashmail.de", "smellfear.com", "smellrear.com", "snakemail.com",
    "sneakemail.com", "sneakymail.de", "snkmail.com", "sofimail.com",
    "sofort-mail.de", "softpls.asia", "sogetthis.com", "soodonims.com",
    "spam.la", "spam.su", "spam4.me", "spamavert.com",
    "spambob.com", "spambob.net", "spambob.org", "spambog.com",
    "spambog.de", "spambog.ru", "spambox.info", "spambox.irishspringrealty.com",
    "spambox.us", "spamcannon.com", "spamcannon.net", "spamcero.com",
    "spamcorptastic.com", "spamcowboy.com", "spamcowboy.net",
    "spamcowboy.org", "spamday.com", "spamex.com", "spamfighter.cf",
    "spamfighter.ga", "spamfighter.gq", "spamfighter.ml",
    "spamfighter.tk", "spamfree24.com", "spamfree24.de",
    "spamfree24.eu", "spamfree24.info", "spamfree24.net",
    "spamfree24.org", "spamgoes.in", "spamgourmet.com",
    "spamgourmet.net", "spamgourmet.org", "spamherelots.com",
    "spamhereplease.com", "spamhole.com", "spamify.com",
    "spaminator.de", "spamkill.info", "spaml.com", "spaml.de",
    "spammotel.com", "spamobox.com", "spamoff.de", "spamslicer.com",
    "spamspot.com", "spamstack.net", "spamthis.co.uk", "spamtrap.ro",
    "spamtrail.com", "spamwc.de", "speedgaus.net", "sperke.net",
    "spikio.com", "spoofmail.de", "squizzy.de", "sry.li",
    "stinkefinger.net", "stop-my-spam.cf", "stop-my-spam.com",
    "stop-my-spam.ga", "stop-my-spam.ml", "stop-my-spam.tk",
    "streetwisemail.com", "stuffmail.de", "supergreatmail.com",
    "supermailer.jp", "superrito.com", "superstachel.de",
    "suremail.info", "svk.jp", "sweetxxx.de", "tafmail.com",
    "tafoi.gr", "tagyoureit.com", "talkinator.com", "tapchicuoihoi.com",
    "teewars.org", "teleworm.com", "teleworm.us", "temp-mail.org",
    "temp-mail.ru", "tempalias.com", "tempe4mail.com", "tempemail.biz",
    "tempemail.co.za", "tempemail.com", "tempemail.net",
    "tempinbox.com", "tempinbox.co.uk", "tempmail.eu", "tempmail.it",
    "tempmail2.com", "tempmaildemo.com", "tempmailer.com",
    "tempmailer.de", "tempomail.fr", "temporarily.de",
    "temporarioemail.com.br", "temporaryemail.net",
    "temporaryemail.us", "temporaryforwarding.com",
    "temporaryinbox.com", "temporarymailaddress.com", "tempthe.net",
    "temptmail.com", "thankmail.net", "thankyou2010.com",
    "thc.st", "thecloudindex.com", "thelimestones.com",
    "thisisnotmyrealemail.com", "thismail.net", "throwawayemailaddress.com",
    "tilien.com", "tittbit.in", "tizi.com", "tmailinator.com",
    "toiea.com", "tradermail.info", "trash-amil.com", "trash-mail.at",
    "trash-mail.com", "trash-mail.de", "trash2009.com", "trash2010.com",
    "trash2011.com", "trashdevil.com", "trashdevil.de",
    "trashemail.de", "trashmail.at", "trashmail.com", "trashmail.de",
    "trashmail.me", "trashmail.net", "trashmail.org",
    "trashmailer.com", "trashymail.com", "trashymail.net",
    "trialmail.de", "trickmail.net", "trillianpro.com",
    "tttreeemail.com", "turboprinz.de", "turual.com",
    "twinmail.de", "tyldd.com", "uggsrock.com", "umail.net",
    "upliftnow.com", "uplipht.com", "venompen.com",
    "veryreallyfakemail.com", "viditag.com", "viewcastmedia.com",
    "viewcastmedia.net", "viewcastmedia.org", "vomoto.com",
    "vubby.com", "wasteland.rfc822.org", "webemail.me",
    "webm4il.info", "webuser.in", "wee.my", "weg-werf-email.de",
    "wegwerfadresse.de", "wegwerfemail.com", "wegwerfemail.de",
    "wegwerfmail.de", "wegwerfmail.net", "wegwerfmail.org",
    "wetrainbayarea.com", "wetrainbayarea.org", "wh4f.org",
    "whatiaas.com", "whatpaas.com", "whyspam.me", "wickmail.net",
    "wilemail.com", "willhackforfood.biz", "willselfdestruct.com",
    "winemaven.info", "wronghead.com", "wuzup.net", "wuzupmail.net",
    "wwwnew.eu", "x.ip6.li", "xagloo.com", "xemaps.com",
    "xents.com", "xjoi.com", "xmaily.com", "xoxy.net",
    "yapped.net", "yeah.net", "yep.it", "yogamaven.com",
    "yomail.info", "yopmail.com", "yopmail.fr", "yopmail.net",
    "yourdomain.com", "ypmail.webarnak.fr.eu.org", "yuurok.com",
    "z1p.biz", "za.com", "zehnminutenmail.de", "zippymail.info",
    "zoaxe.com", "zoemail.org", "zomg.info", "zxcv.com",
    "zxcvbnm.com", "zzz.com",
];

/// Check if domain is disposable
pub fn is_disposable(domain: &str) -> bool {
    let lower = domain.to_lowercase();
    DISPOSABLE_DOMAINS.iter().any(|&d| d == lower)
}
